' Project: HelloWorld
' Type: Single File
' Generated by NextBuild Project Creator

'!org=$8000
'!heap=4096

' Include NextLib if needed (uncomment)
'#include "nextlib.bas"

' Hover over any key word, press F1 for help
' f5 to compile and run 

main()

do : loop           ' we loop forever, as we loaded with a nex which 
                    ' wont exit to basic cleanly!...

sub main()
    
    border 0 : cls

    print at 0,0; "hello from hellonextbuildstudio!"

    ' main loop or program logic here
    do
        ' example: check for key press to exit
        if inkey$ <> "" then exit do
    loop

    border 2 

end sub
