' Project: ModuleDemoII
' Type: Module Project - Master File
' Generated by NextBuild Project Creator

' ------------------------------------------------------------------------------
' - NextBuild Studio
' ------------------------------------------------------------------------------
' - Main module ----------------------------------------------------------------
' ------------------------------------------------------------------------------
'
'  This is the "orchestrator" or Master.NEX part of the module system. This is 
'  the main NEX that will be excuted and control which modules load and run. 
'  It *must* be call Master.bas for NBS to detect module compilation is required
'  It is best to place any interrupt routines within the Master.NEX if you are 
'  using them. Load all your assets into the NEX file by using LoadSDBank() -  

'!org=57344				
'!opt=4
'!heap=1024

' ORG 57344 - $E000 
' Usable memory from $e000 to $ffff minus heap size

' 1024 bytes reserved for variables @ $4000 bank 24
' VarAddress located at $4000

' ULA is paged out and banks 24/25 live in slots 2&3 on start of modules
' For tilemap functions the relevants pages are put back 

' - Includes -------------------------------------------------------------------
#define NOSP 					' do not use the default SP location 
#define IM2
#define DEBUG  					' enable debug routines 
#define NEX 					' we are creating a NEX 
#include <nextlib.bas>
#include <nextlib_ints_ctc2.bas>
#include "includes/globals.bas"

' - Populate RAM banks for generating a NEX ------------------------------------
LoadSDBank("[]font1.spr",0,0,0,28)	' font 8 into bank 28
LoadSDBank("mouse.spr",0,0,0,26)	' This is the mouse sprite in bank 26/27
LoadSDBank("aterix_font.fnt",0,0,0,28)	' This is the text font in bank 28/29
LoadSDBank("sfzii.nxt",0,0,0,29)	' This is the text font in bank 28/29
LoadSDBank("forest.pt3",0,0,0,56) 				' load music.pt3 into bank 
LoadSDBank("lemotree.pt3",0,0,0,57) 				' load music.pt3 into bank 
LoadSDBank("module3.pt3",0,0,0,58) 				' load music.pt3 into bank 
LoadSDBank("module4.pt3",0,0,0,59) 				' load music.pt3 into bank 
LoadSDBank("ts4000.bin",0,0,0,37) 				' load the music replayer into bank 
LoadSDBank("game.afb",0,0,0,38) 				' load music.pt3 into bank 
LoadSDBank("output.dat",0,0,0,60) 				' load music.pt3 into bank 
LoadSDBank("TESKO.PT3",0,0,0,80) 				' load music.pt3 into bank 
'
LoadSDBank("vumeters.spr",0,0,0,81)             ' vu meters 

' - Main Entry -----------------------------------------------------------------
InitInterupts(38,37,80)			' set up interrupts sfxbank, playerbank, music bank 

Main()

sub Main()

	' Initialization here...
	' Prepare empty RAM 

	asm 
		; ensure interrupts are disabled 
		di 
		nextreg MMU2_4000_NR_52,24					; page in alternate banks for $6000-$DFFF
		nextreg MMU3_6000_NR_53,25					; we will use pages 24 & 25 
		; wipe ram 
		ld 		hl,$4000 							; lets make sure they're empty
		ld 		de,$4001 
		ld 		hl,(0)
		ld 		bc,$7d00 
		ldir 	
	end asm 

	' Start with module 1 
	SetLoadModule(ModuleSample2,0,0)				' set the current module to module 1
	
	' Now control will be handed over to the modules 

	do 
		ExecModule(VarLoadModule)
	loop 

end sub

' Execute module id
sub ExecModule(id as ubyte)

	' This subroutine loads the correct module from SD
	' stores the stack and then jumps to $6000. when the 
	' module has finished, execution should return and the
	' stack restored. 

	dim file$ as string 

	' we will use NStr() instead of Str(). NStr() does not rely on ROM routine
	' and is much smaller than the full string library 
	common$=NStr(VarLoadModule)					

	file$="module"+common$+".bin"				' aseemble the complete filename to load

	LoadSD(file,24576,$7d00,0)					' load from SD to $6000

	asm 
		; call the routine
		ld 		(execmodule_end+1),sp 			; write the current stack to the label below
		call 	24576							; call the module 
	execmodule_end:
		ld		sp,0000							; smc from above 
	end asm 

end sub

sub InitInterupts(byval sfxbank as ubyte, byval plbank as ubyte, byval musicbank as ubyte)
	 
	InitSFX(sfxbank)						        ' init the SFX engine, sfx are in bank 36
	InitMusic(plbank,musicbank,3814)		        ' init the music engine 33 has the player, 34 the pt3, 3815 is the offset to the second module
	SetUpCTC()							            ' init the IM2 code 
	 
	PlaySFX(255)                                    	' Plays SFX 
	EnableMusic
	EnableSFX
    
end sub 


ctc_sample_table:
asm 
ctc_sample_table:

	dw $3c00,0,4417 ; 0jump.pcm
	dw $3c00,4417,7516 ; 1pickup.pcm
	dw $3d00,11933-8192,7086 ; 3punch.pcm
	dw $3e00,2635,3238 ; 4dead.pcm
	dw $3e00,5873,11000 ; complete.pcm
end asm 