' Project: ModuleDemoII
' Type: Module Project - Module 002
' Generated by NextBuild Project Creator

' ------------------------------------------------------------------------------
' Nextbuild Studio Module
'
' ORG 24576 - $6000
' Usable memory from $6000 to $dd00 minus Heap size 32kB yeah

'!master=Master.NEX
'!org=24576
'!heap=1024
'!module 
'!noemu

#define IM2
#define NOSP 
#include <nextlib.bas>					' stanbdard nextlib include 
#include "includes/globals.bas"			' Common routines used in all modules 
#include <nextlib_ints_ctc2.bas>
#include "includes/inc-mouse.bas"

	dim	key 			as ubyte 
	dim b 				as ubyte
	dim c 				as ubyte
    dim mox 			as ubyte 
    dim sinoff 			as ubyte
    dim sinspeed 		as ubyte 
	dim k               as string
	dim basex, basey    as ubyte
	dim kdown,n         as ubyte 

	dim a1,b1,c1        as ubyte 
	dim a2,b2,c2        as ubyte 

	basex = 124 : basey = 132 

Init()
Main()

End 		' Exit module 

' This is the intialisation of the module 

Sub Init()
	InitSprites2(64,0,81)		' init sprites in bank 81
	asm 
		nextreg SPRITE_CONTROL_NR_15,%00000011
		ei
	end asm 
	PlayMusic()
	InitLayer2(MODE256X192)
end sub 

Sub Main()
	' Show parameters
		
	L2Text(0,0,"MODULE 2",29,255)
	L2Text(0,1,"MOUSE "+NStr(mox)+NStr(moy),29,255)


	L2Text(0,3,"1 - STOP, 2 - PLAY",29,0)
	L2Text(0,4,"4 - TUNE 2, 5 - TUNE 1",29,0)
	L2Text(0,5,"7 - PLAY SAMPLE",29,0)
	L2Text(0,6,"8 - PLAY AY",29,0)

	Do 
		' asm 
		' 	nextreg TRANSPARENCY_FALLBACK_COL_NR_4A,255
		' end asm 
		ProcessMouse()
		UpdatePointer(0)                               ' sprite 16
		UpdateVus()

		L2Text(6,2,NStr(mouse_mox>>3)+NStr(mouse_moy>>3),29,255)
		L2Text(6,1,NStr(mouse_mbutt band 3),29,255)
		' asm 
		' 	nextreg TRANSPARENCY_FALLBACK_COL_NR_4A,0
		' end asm 
		WaitRetrace2(90)

		if mouse_mbutt band 3 =1  
			PlaySFX(49)				' test sound fx '
            
		endif 
        if mouse_mbutt band 3 =2 
            VarLoadModule=ModuleSample1
			' BBREAK
            exit do 
        endif 

		a = GetKey2

		if a = code "1"
			StopMusic()					' stops music'
		elseif a = code "2"
			PlayMusic()					' continues music'
		elseif a = code "4" 
			NewMusic(57,0)				' new tune in bank 56'
		elseif a = code "5"
			NewMusic(56,0)				' new tune in bank 57'
		elseif a = code "6"
			NewMusic(80,3814)				' new tune in bank 57'
		elseif a = code "7"	and key = 0 
			L2Text(0,7,"SAMPLE "+NStr(b),29,255)
			poke $fd3f,b
			if b < 5
				b = b + 1
			else 
				b = 1 
			endif 
			key = 1
		elseif a = code "8"	and key = 0 
			L2Text(0,8,"AY "+NStr(c),29,255)
			PlaySFX(c)
			if c < 95
				c = c + 1
			else 
				c = 1 
			endif 
			key = 1 
		elseif a = 0 
			key = 0 
		endif 
        
	Loop 

END SUB

sub UpdateVus()


    out 65533, 255
    out 65533, 8
    a1 = (in 65533) band 15

    out 65533, 9
    b1 = in 65533 band 15

    out 65533, 10
    c1 = in 65533 band 15

    out 65533, 254
    out 65533, 8
    a2 = in 65533 band 15

    out 65533, 9
    b2 = in 65533 band 15

    out 65533, 10
    c2 = in 65533 band 15

    'L2Text(0,10,str(a1),40,255)

    UpdateSprite(cast(uinteger,basex)   , basey, 0, a1, 0, 0)
    UpdateSprite(cast(uinteger,basex+8) , basey, 1, b1, 0, 0)
    UpdateSprite(cast(uinteger,basex+16), basey, 2, c1, 0, 0)

    UpdateSprite(cast(uinteger,basex)+32, basey, 3, a2, 0, 0)
    UpdateSprite(cast(uinteger,basex)+40, basey, 4, b2, 0, 0)
    UpdateSprite(cast(uinteger,basex)+48, basey, 5, c2, 0, 0)

end sub 

InitMusic(0,0,0)